### ISSUE TITLE
주의 할점 

### ISSUE THREAD

**Issue by iwin2471** [SunSet0418/Google_Login#2]
#1 에서 발견된 몇가지인데 restful짤때 res.send("오류", status code)혹은 res.status(status code).send 이렇게 사용하거나 res.status().json()이렇게해 express4에서 res.status().send이렇게하는걸 권장하더라
그리고또 express에서 권장하는거 req.param('파라미터값')보다 req.params.파라미터값이런식으로 사용하기를 권장함

**Comment by SunSet0418** [comment]
좋은 배울점이군

**Comment by YonghoAhn** [comment]
ㅋㅋㅋ
